// THIS FILE IS AUTOGENERATED. TO UPDATE, RUN
//    dart tool/generate_asset_hashes.dart

const assetHashes = <String, String>{
  'fastimg_windows_arm64.dll': '20e3523d19240c101b97d335bebcc65d',
  'fastimg_windows_x86_64.dll': '33de57e9288f7c94b6c8cac9e4e61e40',
  'libfastimg_android_arm64.so': 'c5840d5582ab9d0bcb0b6642ca68cfa8',
  'libfastimg_android_armv7.so': 'c9d671bd70a49d8df3bd59e6337d1bf5',
  'libfastimg_android_x86_64.so': 'b3e0370517869f874729760d08036240',
  'libfastimg_ios_arm64.dylib': '41ab4656d551dca2d441bb2f23243501',
  'libfastimg_ios_sim_arm64.dylib': '94ec60304962e72b27f67e88e7b453a1',
  'libfastimg_ios_sim_x86_64.dylib': '9b37cfa5ecc3fc78f860607cd761150f',
  'libfastimg_linux_aarch64.so': '38b17dafdc8f0f9b9081ac1836d01523',
  'libfastimg_linux_x86_64.so': 'd14c4e16e0f53649fee574970f2013aa',
  'libfastimg_macos_arm64.dylib': '155c1d0d55acf6fc186bfb879502c2fa',
  'libfastimg_macos_x86_64.dylib': '35d639e034b0bb8155556e764b81b1d5',
};
